<script lang="ts">
	import {
		Activity,
		AlertTriangle,
		Ban,
		BarChart3,
		Bell,
		BookOpen,
		Check,
		CheckCircle,
		ChevronRight,
		FolderOpen,
		CircleDot,
		Clipboard,
		Clock,
		Dices,
		FileText,
		Gamepad2,
		Globe,
		Handshake,
		Hourglass,
		Image,
		KeyRound,
		Link,
		Lock,
		MapPin,
		Monitor,
		MessageSquare,
		Pencil,
		RefreshCw,
		Save,
		ScrollText,
		Swords,
		Users,
		Search,
		Send,
		Settings,
		Shield,
		ShieldCheck,
		Star,
		Tag,
		Timer,
		Trophy,
		User,
		XCircle,
	ArrowLeft,
	Camera,
	Construction,
	Download,
	Eye,
	Flag,
	Flame,
	GitBranch,
	Lightbulb,
	Palette,
	Paperclip,
	Rocket,
	Sparkles,
	Target,
	ThumbsDown,
	ThumbsUp,
	Trash2,
	Unlock,
	Video,
	Wrench,
	Zap,
	} from 'lucide-svelte';
	import type { ComponentType } from 'svelte';

	const iconMap: Record<string, ComponentType> = {
		activity: Activity,
		'alert-triangle': AlertTriangle,
		ban: Ban,
		'bar-chart': BarChart3,
		bell: Bell,
		'book-open': BookOpen,
		check: Check,
		'check-circle': CheckCircle,
		'chevron-right': ChevronRight,
		FolderOpen,
		'circle-dot': CircleDot,
		clipboard: Clipboard,
		clock: Clock,
		dices: Dices,
		'file-text': FileText,
		'folder-open': FolderOpen,
		gamepad: Gamepad2,
		globe: Globe,
		handshake: Handshake,
		hourglass: Hourglass,
		image: Image,
		key: KeyRound,
		link: Link,
		lock: Lock,
		'map-pin': MapPin,
		monitor: Monitor,
		Monitor,
		'message-square': MessageSquare,
		pencil: Pencil,
		'refresh-cw': RefreshCw,
		save: Save,
		'scroll-text': ScrollText,
		swords: Swords,
		users: Users,
		Swords,
		Users,
		search: Search,
		send: Send,
		settings: Settings,
		shield: Shield,
		'shield-check': ShieldCheck,
		star: Star,
		tag: Tag,
		timer: Timer,
		trophy: Trophy,
		user: User,
		'x-circle': XCircle,
		'arrow-left': ArrowLeft,
		'camera': Camera,
		'construction': Construction,
		'download': Download,
		'eye': Eye,
		'flag': Flag,
		'flame': Flame,
		'git-branch': GitBranch,
		'lightbulb': Lightbulb,
		'palette': Palette,
		'paperclip': Paperclip,
		'pin': Pin,
		'rocket': Rocket,
		'sparkles': Sparkles,
		'target': Target,
		'thumbs-down': ThumbsDown,
		'thumbs-up': ThumbsUp,
		'trash': Trash2,
		'unlock': Unlock,
		'video': Video,
		'wrench': Wrench,
		'zap': Zap,
	};

	let { name, size = 16, class: className = '' }: { name: string; size?: number; class?: string } = $props();

	const IconComponent = $derived(iconMap[name]);
</script>

{#if IconComponent}
	<svelte:component this={IconComponent} {size} class="icon icon--{name} {className}" />
{:else if name}
	<span class="icon icon--text {className}">{name}</span>
{/if}
